version: 2.1

orbs:
  yarn: artsy/yarn@6.5.0
  auto: artsy/auto@2.1.0

workflows:
  build_and_verify:
    jobs:
      - yarn/lint
      - yarn/update-cache
      - yarn/type-check
      - yarn/test
      - yarn/run:
          name: danger
          script: danger
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore: master
          requires:
            - yarn/update-cache
            - yarn/test
            - yarn/lint
            - yarn/type-check
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/test
            - yarn/lint
            - yarn/type-check
